site_name: Social Kit Documentation
site_description: Documentation for the Social Kit on Community Content
docs_dir: docs
extra_css:
  - stylesheets/extra.css
theme:
  palette:
    scheme: slate
    primary: blue
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - navigation.expand
  font:
      text: Lato
      code: JetBrains Mono
  
nav:
  - Documentation:
    - index.md
    - quick-start.md
    - Player Markers:
      - player-markers/player-markers.md
      - player-markers/add-hierarchy.md
      - player-markers/bindings.md
      - player-markers/settings.md
    - Player Callouts:
      - player-callouts/player-callouts.md
      - player-callouts/add-hierarchy.md
      - player-callouts/bindings.md
      - player-callouts/creating-callouts.md
      - player-callouts/settings.md
    - Player Pokes:
      - player-pokes/player-pokes.md
      - player-pokes/add-hierarchy.md
      - player-pokes/bindings.md
      - player-pokes/creating-pokes.md
      - player-pokes/settings.md

  - Core Games:
    - https://coregames.com

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - markdown.extensions.codehilite:
      guess_lang: false
